### ISSUE TITLE
Tagged dev commit causing existing repos to suddenly break

### ISSUE THREAD

**Issue by SerialVelocity** [rcorre/jsonizer#16]
Hey,

You tagged v0.2.0 on your dev branch (bad! tag on master!) which was uploaded to code.dlang.org breaking existing code. Was this intentional?

Also, on new versions of D, use package.d, not all.d since it means if I do:

``` d
import jsonizer;
```

then it will import everything from jsonizer.

If you're trying to follow a git methodology, we can talk about one that I find very nice if you want?

**Comment by rcorre** [comment]
No! I wasn't intending for that to happen. I wasn't aware that only tagging on master was a convention, but I'm happy to hear any recommendations.

As far as breaking code, that probably has more to do with my versioning. 
Once I'm more confident in the API (hopefully soon), I will tag v1.0.0 and begin properly following semver conventions. This means that breaking changes like this would constitute a major version bump (1.0.0 -> 2.0.0) rather than a minor version bump (0.1.0 -> 0.2.0), making it less likely that people will get caught off guard.

While I've been in the 0.y.x versions,  I have been bumping the minor version for breaking changes, as otherwise I would end up with a rather high major version by the time the API stabilized.
I was following this from the [semver guidelines](http://semver.org/):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Of course, I probably should have documented that better, using `"jsonizer": "~>0.2.0"` would prevent being surprised by non-backwards-compatible changes.

Sorry for any confusion!

Also, I wasn't aware there was any power to `all.d` beyond it being a convention. Does `import jsonizer` translate to `import jsonizer.all`?

**Comment by SerialVelocity** [comment]
So, what I tend to on my projects (and what I've seen most companies doing as well) is to start with a branch called `develop`. Now, each new feature is done in a branch called `feature/{name of feature}`. All bugfixes are done in `bugfix/{name of bugfix}`. The reason for this, is that when the project gets big enough, it's easy just to say, test feature branches against develop and bugfix branches against release. Now, when you want to make a release, merge into master and tag it. The full version of this methodology is slightly different but for a small project, all of the details aren't needed. That way, all changes are propagated into develop and the master is always stable.

I didn't think that dub would update to the next minor version if I did `~>0.1.0` but it did :/

`all.d` was the convention before `package.d` came along. Now, `import jsonzier;` gets converted into `import jsonizer.package;` if `jsonizer.d` doesn't exist.

**Comment by SerialVelocity** [comment]
You've fixed this by creating `jsonizer/package.d`. Thanks! Only other thing I should point out is you probably want to wrap your imports with `private` otherwise they get exposed by accident (version 0.1.0 exposed fromJSON which I thought had to be used from your library but really it was just from `std.json`)

**Comment by rcorre** [comment]
Imports should be private by default (I don't think there's such a thing as `private import`).
There is no `std.json.fromJSON`, however v0.1.0 did rename `extract` to `toJSON`.
There _are_ still places where I'm exposing more than I need to (certain helper functions like `isOptional` are currently public) and I'm working on limiting the public API to the minimum set of symbols that need to be exposed.
There may be places within the `JsonizeMe` mixin that leak imports but I've tried to scope those as tightly as possible (in more recent versions most imports should exist only within the generated functions).
