### ISSUE TITLE
Unable to construct class with const types

### ISSUE THREAD

**Issue by SerialVelocity** [rcorre/jsonizer#18]
Hey,

I'm unable to construct this class:

``` d
class A {
  mixin JsonizeMe;

  const int a;

  @jsonize
  public this(int a) {
    this.a = a;
  }
}
```

**Comment by rcorre** [comment]
Currently the only option here is to use a custom constructor.
Unless you have a curtom constructor, `JsonizeMe` generates a method that populates a default-constructed object. Since the object is already constructed, I cannot set const/immutable members.

I'll look in to generating a contructor instead, which would allow this, but would require you to choose between either having a generated constructor _or_ a custom constructor (a mixin cannot overload symbols in the surrounding scope).
I don't think this would be an unfair limitation though.

**Comment by SerialVelocity** [comment]
Yes, but the above has a custom constructor marked with `@jsonize`. The field `a` isn't marked with `@jsonize` so it shouldn't even be considered by your code.

**Comment by rcorre** [comment]
Oops, somehow I missed that you are using a custom ctor. The above should definitely work.
